blogdinamico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noticias.urls')),
]

noticias/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'noticias'
urlpatterns = [
    path('', views.ListaNoticiasView.as_view(), name='listar'),
    path('<int:pk>/', views.NoticiaDetalheView.as_view(), name='detalhe'),
    path('busca/', views.busca_noticias, name='buscar'),
    path('criar/', views.CriarNoticiaView.as_view(), name='criar'),
    path('atualizar/<int:pk>/', views.AtualizarNoticiaView.as_view(), name='atualizar'),
    path('excluir/<int:pk>/', views.ExcluirNoticiaView.as_view(), name='excluir'),
    path('historico/', views.HistoricoAcessoView.as_view(), name='historico_acesso'),
    path('login/', auth_views.LoginView.as_view(template_name='noticias/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='noticias:listar'), name='logout'),
    path('registro/', views.RegistroView.as_view(), name='registro'),
    path('categorias/', views.CategoriaListView.as_view(), name='lista_categorias'),
    path('categorias/<int:pk>/', views.CategoriaDetailView.as_view(), name='detalhe_categoria'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Notíciasss!
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal" style="background-color: #171717; color: #FFFFFF; padding: 10px 20px;">
        <nav style="display: flex; justify-content: space-between; align-items: center;">
            <div>
                <a href="/" style="color: #FFFFFF; font-size: 1.5rem;">Blog Notícias - PMR3304</a>
            </div>
            <ul style="list-style: none; display: flex; gap: 20px;">
                <li><a href="{% url 'noticias:listar' %}" style="color: #FFFFFF;">Notícias</a></li>
                <li><a href="{% url 'noticias:lista_categorias' %}">Categorias</a></li>
                {% if user.is_authenticated %}
                    <a href="{% url 'noticias:historico_acesso' %}" style="color: #FFFFFF;">Histórico</a>
                    
                    <!-- Formulário de logout -->
                    <form action="{% url 'noticias:logout' %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" style="background: none; border: none; color: #FFFFFF; cursor: pointer;">
                            Logout
                        </button>
                    </form>
                {% else %}
                    <a href="{% url 'noticias:login' %}" style="color: #FFFFFF;">Login</a>
                    <a href="{% url 'noticias:registro' %}" style="color: #FFFFFF;">Registrar</a>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal" style="background-color: #171717; color: #FFFFFF; padding: 20px; text-align: center;">
        <p>
            <small>Desenvolvido por Gustavo Loiola</small>
        </p>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </footer>
</body>

</html>